### PR TITLE
Add impl std::error::Error for FluentError

### PR DESCRIPTION
**Pull request by guangie88**
Hello @cosmo0920, currently I am using your `fruently` crate, and thanks for your good work! :+1:

I am not sure if you are willing to accept PR, but I would like to add some features as listed below, and hopefully you don't mind.

Changes:
* Add Error trait implementation so that it can be used together with `failure` crate easily.
* Add additional unit test for the trait implementation.

Let me know if you have any comments (e.g. bumping crate version) and thanks!

### CODE REVIEW

**Review by cosmo0920 — COMMENTED** [review]
LGTM. I’ll take a look.
Thank you for your work.

**Comment by guangie88** [comment]
No problem and you are welcome.

**Review by cosmo0920 — APPROVED** [review]
I've read [this article](https://users.rust-lang.org/t/announcing-failure/13895/4) and your test code.
This change is pretty reasonable. :+1:

**Comment by cosmo0920** [comment]
I'd published this change as 0.10.0.
If there is something willing to change this crate, I'll be a pleasure to review and accept your work.
Anyway, thank you for your great work! :smile:

**Comment by guangie88** [comment]
Sure thank you for accepting the PR! 😄
I actually have another minor PR, and will continue from there.

**Pull request merged**
